---

#
# use container-based infrastructure
# @see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
# @see http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
#
sudo: false

#
# testing multiple subdirectories
# @see https://lord.io/blog/2014/travis-multiple-subdirs/
# @see https://www.dominicrodger.com/tox-and-travis.html
#
language: python
env:
    - TOX_ENV=py27-thriftrw05
    - TOX_ENV=py27-thriftrw10
    - TOX_ENV=pypy-thriftrw05
    - TOX_ENV=pypy-thriftrw10
    - TOX_ENV=cover
    - TOX_ENV=flake8
    - TOX_ENV=docs

install:
  - make install

script:
  - make test_ci

after_success:
  - coveralls -v

